name: Run Pytest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies and run pytest
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libpango1.0-dev
        pip install -r requirements.txt
        sudo apt install imagemagick
        magick --version
        pip install pytest
        pytest image_test.py
