name: Run Pytest

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies and run pytest
      run: |
        python -m pip install --upgrade pip
        brew install pango ffmpeg
        brew install imagemagick
        brew install --cask mactex-no-gui
        pip install -r requirements.txt
        pip install .
        pytest image_test.py
